name: cygwin-action-workflow
on: 
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

defaults:
  run:
    shell: cmd
    
jobs:
  build_cygwin:
    strategy:
      matrix:
        os: [windows-2019]
        arch: [x64, x86]
      fail-fast: true

    runs-on: ${{ matrix.os }}
    env:
      cygwinTargetZip: main-${{ github.ref_name }}-cygwin.zip
      
    steps:
      - uses: actions/checkout@v2

      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: ${{ matrix.arch }}
          
      - name: Build test
        run: |
          md build && C:\tools\cygwin\bin\bash.exe -l -c cd %GITHUB_WORKSPACE% && gcc -static main.c -o build\main.exe
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          directory: "build"
          filename: "${{ env.cygwinTargetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/${{ env.cygwinTargetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
